version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["gunicorn", "--bind", ":8000", "--workers", "2", "core.wsgi"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}

  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: myth
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
